import "../styles/luxurySystem.css";
import { useEffect, useRef, useState } from "react";
import { FiArrowLeft, FiCamera, FiCheck, FiEdit3, FiLogIn, FiLogOut, FiPhone, FiSave, FiShield, FiTrash2, FiUser, FiX } from "react-icons/fi";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { toast } from "../utils/toast";
import { changePassword, getMyBookings, getProfile, login, signup, updateProfile, verifyLoginOtp, verifySignupOtp } from "../services/api";
import { useAuth } from "../context/AuthContext";
import localPintuLogo from "../assets/images/main_logo.optimized.webp";
import "../styles/auth.css";
import "../styles/premiumLogin.css";
const PROFILE_DRAFT_KEY = "localpintu-profile-draft";
const blank = { fullName:"", mobileNumber:"", otp:"" };
export function SignupPage(){const [form,setForm]=useState(blank),[step,setStep]=useState("details"),[error,setError]=useState(""),[busy,setBusy]=useState(false),nav=useNavigate(),{login:save}=useAuth();const set=(k,v)=>setForm(p=>({...p,[k]:v}));const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{if(step==="details"){const result=await signup({fullName:form.fullName,mobileNumber:form.mobileNumber});if(result.devOtp)set("otp",result.devOtp);setStep("otp")}else{const data=await verifySignupOtp(form);save(data);nav("/")}}catch(e){setError(e.message)}finally{setBusy(false)}};return <AuthShell title="Create your account" subtitle="Start with your mobile number — it only takes a minute." error={error} loginMode><form className="customer-login-form customer-signup-form" onSubmit={submit}>{step==="details"?<><label className="auth-input-field"><span>Full name</span><div><FiUser/><input autoComplete="name" placeholder="Enter your full name" value={form.fullName} onChange={e=>set("fullName",e.target.value)} required/></div></label><label className="auth-input-field"><span>Mobile number</span><div><FiPhone/><input inputMode="numeric" autoComplete="tel" placeholder="Enter 10-digit mobile" value={form.mobileNumber} onChange={e=>set("mobileNumber",e.target.value.replace(/\D/g,"").slice(0,10))} required/></div></label></>:<label className="auth-input-field"><span>Verification OTP</span><div><FiShield/><input inputMode="numeric" autoComplete="one-time-code" placeholder="Enter 6-digit OTP" value={form.otp} onChange={e=>set("otp",e.target.value.replace(/\D/g,"").slice(0,6))} required/></div></label>}<button className="customer-login-submit" disabled={busy}><FiLogIn/>{busy?"Please wait...":step==="details"?"Send OTP":"Verify & create account"}</button></form><div className="auth-new-account"><span>Already have an account?</span><Link to="/login">Log in</Link></div><div className="auth-trust"><FiShield/><span>Your details are protected and never shared.</span></div></AuthShell>}
export function LoginPage(){const [form,setForm]=useState({mobileNumber:"",otp:""}),[step,setStep]=useState("mobile"),[error,setError]=useState(""),[busy,setBusy]=useState(false),submitting=useRef(false),nav=useNavigate(),[params]=useSearchParams(),{login:save}=useAuth();const submit=async e=>{e.preventDefault();if(submitting.current)return;submitting.current=true;setBusy(true);setError("");try{if(step==="mobile"){const result=await login({mobileNumber:form.mobileNumber});if(result.devOtp)setForm(p=>({...p,otp:result.devOtp}));setStep("otp")}else{const data=await verifyLoginOtp(form);save(data);nav(params.get("returnTo")||"/")}}catch(e){setError(e.message)}finally{submitting.current=false;setBusy(false)}};return <AuthShell title="Welcome back" subtitle="Log in securely with your mobile OTP" error={error} loginMode><form className="customer-login-form" onSubmit={submit}><label className="auth-input-field"><span>{step==="mobile"?"Mobile number":"Verification OTP"}</span><div><FiLogIn/><input inputMode="numeric" autoComplete={step==="mobile"?"tel":"one-time-code"} placeholder={step==="mobile"?"Enter 10-digit mobile":"Enter 6-digit OTP"} value={step==="mobile"?form.mobileNumber:form.otp} onChange={e=>setForm({...form,[step==="mobile"?"mobileNumber":"otp"]:e.target.value.replace(/\D/g,"").slice(0,step==="mobile"?10:6)})} required/></div></label><button className="customer-login-submit" disabled={busy}><FiLogIn/>{busy?"Please wait...":step==="mobile"?"Send OTP":"Verify & login"}</button></form><div className="auth-new-account"><span>New to LocalPintu?</span><Link to="/signup">Create an account</Link></div><div className="auth-trust"><FiShield/><span>Your OTP and account information are protected.</span></div></AuthShell>}
const profileFields = [
  ["fullName", "Full name", "text"], ["email", "Email address", "email"], ["mobileNumber", "Mobile number", "tel"],
  ["address", "Service address", "text"], ["state", "State", "text"], ["city", "City", "text"], ["pincode", "Pincode", "text"],
];
const resizeProfileImage = (file) => new Promise((resolve, reject) => {
  if (!file?.type?.startsWith("image/")) return reject(new Error("Please choose a JPG, PNG or WebP image."));
  if (file.size > 8 * 1024 * 1024) return reject(new Error("Image must be smaller than 8 MB."));
  const reader = new FileReader();
  reader.onerror = () => reject(new Error("Unable to read this image."));
  reader.onload = () => { const image = new Image(); image.onerror = () => reject(new Error("This image could not be opened.")); image.onload = () => { const size = Math.min(640, Math.max(image.width, image.height)); const scale = Math.min(1, size / Math.max(image.width, image.height)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext("2d").drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL("image/jpeg", .84)); }; image.src = reader.result; };
  reader.readAsDataURL(file);
});
export function ProfilePage(){
  const {customer,setCustomer,logout}=useAuth(),nav=useNavigate();
  const [storedDraft]=useState(()=>{try{return JSON.parse(sessionStorage.getItem(PROFILE_DRAFT_KEY)||"null")}catch{return null}});
  const [profile,setProfile]=useState(storedDraft||customer||{}),[original,setOriginal]=useState(customer||{}),[bookings,setBookings]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[edit,setEdit]=useState(Boolean(storedDraft)),[busy,setBusy]=useState(false);
  useEffect(()=>{let alive=true;getProfile().then(p=>{if(alive){setProfile(current=>storedDraft?{...p,...current}:p);setOriginal(p);setCustomer(p)}}).catch(e=>alive&&setError(e.message));getMyBookings().then(value=>alive&&setBookings(value)).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[setCustomer,storedDraft]);
  const change=(key,value)=>setProfile(current=>({...current,[key]:value}));
  const chooseImage=async(event)=>{const file=event.target.files?.[0];if(!file)return;setError("");try{change("profileImage",await resizeProfileImage(file))}catch(e){setError(e.message)}finally{event.target.value=""}};
  const save=async(event)=>{event.preventDefault();const payload=Object.fromEntries([...profileFields.map(([key])=>[key,String(profile?.[key]||"").trim()]),["profileImage",profile?.profileImage||""]]);const validation=!payload.fullName||payload.fullName.length<2?"Enter your full name.":!/^[^\s@]+@[^\s@]+[.][^\s@]+$/.test(payload.email)?"Enter a valid email address.":!/^[0-9]{10}$/.test(payload.mobileNumber)?"Mobile number must contain 10 digits.":!payload.address||!payload.state||!payload.city?"Address, state and city are required.":!/^[0-9]{6}$/.test(payload.pincode)?"Pincode must contain 6 digits.":"";if(validation){setError(validation);toast.error("Profile not saved",{description:validation});return}setBusy(true);setError("");setMessage("");try{const updated=await updateProfile(payload);setProfile(updated);setOriginal(updated);setCustomer(updated);setEdit(false);sessionStorage.removeItem(PROFILE_DRAFT_KEY);setMessage("Profile updated successfully.");toast.success("Profile updated",{description:"Your latest details have been saved."})}catch(e){if(e.status===401||/invalid|expired token/i.test(e.message)){sessionStorage.setItem(PROFILE_DRAFT_KEY,JSON.stringify(payload));toast.error("Session expired",{description:"Please log in again. Your profile changes are safe."});nav("/login?returnTo=%2Fprofile");return}setError(e.message);toast.error("Profile not saved",{description:e.message})}finally{setBusy(false)}};
  const cancel=()=>{setProfile(original);setEdit(false);setError("");setMessage("")};
  const initials=String(profile?.fullName||"LP").split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();
  return <AuthShell title="My Profile" error={error} message={message}><section className="profile-overview"><div className="profile-avatar">{profile?.profileImage?<img src={profile.profileImage} alt={`${profile.fullName||"Customer"} profile`}/>:<span>{initials}</span>}{edit&&<label className="profile-camera" title="Choose profile photo"><FiCamera/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage}/></label>}</div><div><span>LocalPintu customer</span><h2>{profile?.fullName||"Your profile"}</h2><p>{profile?.email||"Keep your contact details up to date"}</p></div>{!edit&&<button className="profile-edit-button" type="button" onClick={()=>{setEdit(true);setMessage("")}}><FiEdit3/> Edit profile</button>}</section>{edit&&profile?.profileImage&&<button className="profile-remove-photo" type="button" onClick={()=>change("profileImage","")}><FiTrash2/> Remove photo</button>}<form className="profile-form" onSubmit={save} noValidate>{profileFields.map(([key,label,type])=><label key={key} className={key==="address"?"profile-field profile-field--wide":"profile-field"}><span>{label}</span><input type={type} inputMode={key==="mobileNumber"||key==="pincode"?"numeric":undefined} disabled={!edit} value={profile?.[key]||""} onChange={event=>change(key,key==="mobileNumber"?event.target.value.replace(/\D/g,"").slice(0,10):key==="pincode"?event.target.value.replace(/\D/g,"").slice(0,6):event.target.value)} required/></label>)}{edit&&<>{error&&<div className="profile-save-feedback">{error}</div>}<div className="profile-form-actions"><button className="profile-cancel" type="button" onClick={cancel} disabled={busy}><FiX/> Cancel</button><button type="submit" disabled={busy}><FiSave/> {busy?"Saving...":"Save changes"}</button></div></>}</form><section className="auth-bookings"><div className="profile-section-title"><div><span>Service history</span><h2>My bookings</h2></div><strong>{bookings.length}</strong></div>{bookings.length?bookings.map(booking=><p key={booking._id}>{booking.bookingNumber} · {booking.status}{booking.technicianId?` · Technician: ${booking.technicianId.fullName} (${booking.technicianId.mobileNumber})`:""}</p>):<div className="profile-empty"><FiCheck/><span>No bookings yet</span></div>}</section><div className="profile-account-actions"><Link className="auth-link-button" to="/change-password"><FiUser/> Change password</Link><button type="button" className="auth-secondary" onClick={async()=>{await logout();nav("/")}}><FiLogOut/> Log out</button></div></AuthShell>
}
export function ChangePasswordPage(){const [form,setForm]=useState({currentPassword:"",newPassword:"",confirmPassword:""}),[error,setError]=useState(""),[message,setMessage]=useState("");const submit=async e=>{e.preventDefault();try{await changePassword(form);setMessage("Password changed successfully");setForm({currentPassword:"",newPassword:"",confirmPassword:""})}catch(e){setError(e.message)}};return <AuthShell title="Change password" error={error} message={message}><form onSubmit={submit}>{Object.keys(form).map(k=><input key={k} type="password" placeholder={k.replace(/([A-Z])/g," $1")} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required/>)}<button>Update password</button></form></AuthShell>}
function AuthShell({title,subtitle,error,message,children,loginMode=false}){return <main className={`auth-page${loginMode?" customer-login-page":""}`}><section className={`auth-card${loginMode?" customer-login-card":""}`}><Link className="auth-back-link" to="/"><FiArrowLeft/> Back to home</Link>{loginMode&&<div className="auth-brand"><span><img src={localPintuLogo} alt="LocalPintu logo" /></span><div><strong>LocalPintu</strong><small>Trusted home services</small></div></div>}<h1>{title}</h1>{subtitle&&<p className="auth-subtitle">{subtitle}</p>}{error&&<p className="auth-error">{error}</p>}{message&&<p className="auth-success">{message}</p>}{children}</section></main>}






