import "../styles/luxurySystem.css";
import { motion } from "framer-motion";
import { FiArrowRight, FiCheck, FiMapPin, FiMinus, FiPlus, FiShoppingBag, FiTrash2 } from "react-icons/fi";
import { Link } from "react-router-dom";
import Nav from "../layouts/nav";
import Footer from "../layouts/Footer";
import { useCart } from "../context/CartContext";
import { EmptyState } from "../components/AsyncStates";
import { usePriceBreakdown } from "../hooks/usePricingSettings";
import "../styles/commerce.css";
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
export default function CartPage() {
  const cart = useCart();
  const pricing = usePriceBreakdown(cart.serviceSubtotal, cart.productSubtotal, 0, cart.servicePlatformFee);
  return <><Nav /><main className="commerce-page"><header className="commerce-hero"><span>Your service bag</span><h1>Review your selected care</h1><p>Services and technician-recommended parts, together in one transparent summary.</p></header>
    {!cart.count ? <EmptyState title="Your cart is waiting" message="Explore service plans and add the right care for your home." action={<Link className="primary-action" to="/applications">Explore services</Link>} /> : <div className="cart-layout"><section className="cart-list">
      {cart.items.map((item, index) => { const quantity = Math.max(1, Number(item.quantity || 1)); const unitPrice = Number(item.offerPrice ?? item.price ?? 0); return <motion.article className="cart-item" key={item.planId} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} layout>{item.image ? <img src={item.image} alt="" loading="lazy" /> : <div className="cart-image-placeholder"><FiShoppingBag /></div>}<div className="cart-item-copy"><span>Service · {item.categoryTitle}</span><h2>{item.planTitle}</h2><p>{item.childTitle}</p><div className="included"><FiCheck /> Selected service price included</div></div><div className="cart-item-price"><motion.strong key={quantity} initial={{ scale: .82, opacity: .35 }} animate={{ scale: 1, opacity: 1 }} transition={{ type: "spring", stiffness: 520, damping: 24 }}>{money(unitPrice * quantity)}</motion.strong>{Number(item.price) > Number(item.offerPrice) && <del>{money(Number(item.price) * quantity)}</del>}<div className="service-quantity" aria-label={`${item.planTitle} quantity`}><button type="button" onClick={() => cart.updateItemQuantity(item.planId, quantity - 1)} aria-label="Decrease quantity"><FiMinus /></button><motion.span key={quantity} initial={{ y: -8, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ type: "spring", stiffness: 500, damping: 25 }}>{quantity}</motion.span><button type="button" onClick={() => cart.updateItemQuantity(item.planId, quantity + 1)} aria-label="Increase quantity"><FiPlus /></button></div><button onClick={() => cart.removeItem(item.planId)}><FiTrash2 /> Remove</button></div></motion.article>; })}
      {cart.productItems.map((item, index) => <motion.article className="cart-item cart-product-item" key={item.productId} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: (cart.items.length + index) * .05 }}><img src={item.image} alt={item.name} loading="lazy" /><div className="cart-item-copy"><span>Recommended product</span><h2>{item.name}</h2><p>Compatibility will be confirmed by your assigned technician.</p><div className="included"><FiCheck /> {item.warrantyDays || 0}-day product warranty</div></div><div className="cart-item-price"><strong>{money(item.price)}</strong>{Number(item.mrp) > Number(item.price) && <del>{money(item.mrp)}</del>}<button onClick={() => cart.removeProduct(item.productId)}><FiTrash2 /> Remove</button></div></motion.article>)}
    </section><aside className="price-card"><span>Order summary</span><div><p>Service Charges (before GST)</p><strong>{money(pricing.subtotal)}</strong></div>{pricing.platformFeeEnabled&&pricing.platformFee>0&&<div><p>Platform Fee (before GST)</p><strong>{money(pricing.platformFee)}</strong></div>}{pricing.gstEnabled&&<div><p>GST ({pricing.gstPercentage}%)</p><strong>{money(pricing.gstAmount)}</strong></div>}<div className="grand-total"><p>Total Payable</p><strong>{money(pricing.totalAmount)}</strong></div><ul><li><FiCheck /> GST calculated separately</li><li><FiCheck /> Upfront plan pricing</li><li><FiCheck /> Product fitment confirmed before installation</li><li><FiMapPin /> Service at your address</li></ul>{cart.items.length ? <Link className="primary-action" to="/checkout">Proceed to checkout <FiArrowRight /></Link> : <Link className="primary-action" to="/applications">Add a service first <FiArrowRight /></Link>}<Link className="text-action" to="/#home-services">Continue browsing</Link></aside></div>}
  </main><Footer /></>;
}
