import { useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { FiArrowRight, FiCheckCircle, FiChevronDown, FiClock, FiCreditCard, FiHelpCircle, FiMapPin, FiMessageCircle, FiSearch, FiShield, FiTool } from "react-icons/fi";
import Nav from "../layouts/nav";
import Footer from "../layouts/Footer";
import "../styles/faqs.css";

const FAQS = [
  { category: "Booking", q: "How do I book a home service with LocalPintu?", a: "Choose a service, select the plan that suits your requirement, add it to your cart, enter the visit address and pick an available date and time slot. Your booking details stay available in My Orders." },
  { category: "Booking", q: "Can I see the price before I place my booking?", a: "Yes. Each available plan shows its service price and any applicable visit charge before it is added to your cart. Review the full order summary before confirming your booking." },
  { category: "Booking", q: "Which home services can I book in Jaipur?", a: "Available options may include appliance repair, AC care, water purifier service, plumbing, electrical work, carpentry and other home-care services. The live catalogue shows the services currently available." },
  { category: "Booking", q: "How do I know whether my address is serviceable?", a: "Enter your exact Jaipur location and six-digit pincode during booking. LocalPintu checks live availability for the selected pincode before allowing the service request to proceed." },
  { category: "Technician", q: "When will a technician be assigned to my booking?", a: "After a booking is confirmed, LocalPintu matches it with an eligible technician based on service, availability and service location. You can view assignment and job-progress updates in My Orders." },
  { category: "Technician", q: "Can I view the assigned technician's details?", a: "Once a technician is assigned, the booking details show the available professional profile information, including name, expertise, rating and contact option where provided." },
  { category: "Technician", q: "How is service completion verified?", a: "For eligible jobs, completion is confirmed through the secure booking flow after the work is finished. Please verify the completed work before sharing any OTP or approval." },
  { category: "Payments", q: "Which payment methods are available?", a: "The checkout shows the payment methods enabled for your booking. Where cash-on-service is available, the booking will clearly show the amount as payable at the visit; online payments are marked paid only after secure gateway confirmation." },
  { category: "Payments", q: "What if my online payment is still processing?", a: "Do not place the same booking again immediately. Open My Orders to check the payment state. If your bank shows a debit but the booking remains pending, contact LocalPintu support with your booking number." },
  { category: "Payments", q: "Will I receive booking and payment information?", a: "Your booking record contains the selected service, visit timing, payment state and reference information when available. Keep your booking number handy whenever you contact support." },
  { category: "Changes", q: "Can I change my date, time slot or address after booking?", a: "Availability can change once a technician is being matched. Contact support as early as possible with your booking number; the team can guide you on the available next step for that booking." },
  { category: "Changes", q: "What if I need to cancel a booking?", a: "Open the booking in My Orders and contact LocalPintu support with the booking number before the scheduled visit. The team will confirm the options available for that booking and its payment state." },
  { category: "Support", q: "How can I track my service request?", a: "Sign in with the account used for booking and open My Orders. You can see your scheduled visit, booking status, payment state and technician information once assigned." },
  { category: "Support", q: "What should I do if I need help during a service visit?", a: "Use the support contact shown on the website and share your booking number. For safety concerns, stop using the appliance or affected electrical fitting until a qualified professional has checked it." },
  { category: "Support", q: "How do I contact LocalPintu?", a: "Use the Contact Us page, call the customer-care number shown in the website footer, or email the support team. Sharing your booking number helps the team locate the right request quickly." },
];

const CATEGORIES = ["All", ...new Set(FAQS.map((item) => item.category))];

export default function Faqs() {
  const [category, setCategory] = useState("All");
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(0);
  const filtered = useMemo(() => FAQS.filter((item) => (category === "All" || item.category === category) && `${item.q} ${item.a}`.toLowerCase().includes(query.trim().toLowerCase())), [category, query]);
  const site = (import.meta.env.VITE_SITE_URL || "https://localpintu.com").replace(/\/$/, "");
  const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: FAQS.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) };

  return <><Nav /><main className="faq-page">
    <Helmet><title>Frequently Asked Questions | LocalPintu Jaipur</title><meta name="description" content="Find answers about LocalPintu booking, pricing, Jaipur pincode availability, payments, technician assignment, tracking and customer support." /><link rel="canonical" href={`${site}/faqs`} /><meta property="og:type" content="website" /><meta property="og:title" content="Frequently Asked Questions | LocalPintu Jaipur" /><meta property="og:description" content="Clear answers about booking, pricing, payments, technicians and support." /><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
    <section className="faq-hero"><div className="faq-hero__copy"><span><FiHelpCircle /> LocalPintu help centre</span><h1>Answers, before you need to ask.</h1><p>Everything you need to know about booking trusted doorstep home services in Jaipur.</p><div className="faq-hero__proof"><span><FiShield /> Secure booking flow</span><span><FiClock /> Track service updates</span><span><FiMapPin /> Pincode availability</span></div></div><div className="faq-hero__card"><i><FiMessageCircle /></i><small>Need an answer now?</small><strong>Our care team is here to help.</strong><Link to="/contact">Contact support <FiArrowRight /></Link></div></section>
    <section className="faq-content" aria-labelledby="faq-title"><header><span>Help, made simple</span><h2 id="faq-title">Frequently asked questions</h2><p>Search a question or choose a topic to find a clear answer.</p></header><div className="faq-toolbar"><label><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search booking, payment, technician..." aria-label="Search frequently asked questions" />{query ? <button type="button" onClick={() => setQuery("")}>Clear</button> : null}</label><div className="faq-filters" aria-label="FAQ categories">{CATEGORIES.map((item) => <button type="button" className={category === item ? "is-active" : ""} onClick={() => { setCategory(item); setOpen(0); }} key={item}>{item}</button>)}</div></div><div className="faq-layout"><div className="faq-list">{filtered.length ? filtered.map((item, index) => { const id = `${item.category}-${index}`; const expanded = open === id; return <article className={expanded ? "is-open" : ""} key={item.q}><button type="button" aria-expanded={expanded} onClick={() => setOpen(expanded ? "" : id)}><span><small>{item.category}</small><strong>{item.q}</strong></span><FiChevronDown /></button>{expanded ? <div><p>{item.a}</p></div> : null}</article>; }) : <div className="faq-empty"><FiSearch /><strong>No matching answer found</strong><p>Try another word, or contact our care team for booking help.</p><Link to="/contact">Contact support <FiArrowRight /></Link></div>}</div><aside className="faq-side"><div><FiTool /><small>Ready to book?</small><h3>Find the right service for your home.</h3><p>Explore live service plans and select a convenient visit slot.</p><Link to="/#home-services">Explore services <FiArrowRight /></Link></div><div><FiCreditCard /><small>Already booked?</small><h3>Keep your booking number ready.</h3><p>It helps support quickly find your service request and payment status.</p><Link to="/orders">View my orders <FiArrowRight /></Link></div><div><FiCheckCircle /><small>Useful reading</small><h3>Get practical home-care tips.</h3><Link to="/blogs">Read expert guides <FiArrowRight /></Link></div></aside></div></section>
  </main><Footer /></>;
}
