import { Link, useLocation } from "react-router-dom";
import Nav from "../layouts/nav";
import Footer from "../layouts/Footer";
import "../styles/legal.css";

const Contact = () => <><a href="mailto:info@localpintu.com">info@localpintu.com</a> or <a href="tel:+917023320977">+91 70233 20977</a></>;
const policies = {
  "/privacy-policy": { eyebrow: "YOUR DATA, RESPECTED", title: "Privacy Policy", intro: "This Privacy Policy explains how LocalPintu Repair Services (\"LocalPintu\", \"we\", \"us\" or \"our\") collects, uses, shares and protects personal information when you visit our website, contact us or use our doorstep services.", sections: [
    ["1. Information We Collect", <><p>We collect only information reasonably required to respond to your request, arrange a service visit, process a booking and provide customer support. This may include:</p><ul><li>Your name, mobile number, email address and service address;</li><li>Appliance, repair, installation or maintenance details, including model information and the issue reported;</li><li>Booking history, communications through phone, WhatsApp or email, and feedback you choose to provide;</li><li>Payment, invoice and transaction-reference information where applicable; and</li><li>Basic technical information such as browser type, device information, IP address and website-usage data collected through cookies or similar tools.</li></ul><p>We do not collect or store your card number, UPI PIN, CVV, internet-banking password or other sensitive payment credentials. Online payments, where available, are processed by authorised payment partners.</p></>],
    ["2. How We Use Your Information", <><p>Your information is used only for legitimate service-related purposes, including to:</p><ul><li>Verify your request, confirm appointments and assign an appropriate technician;</li><li>Contact you about bookings, arrival updates, estimates, invoices, warranty support and follow-ups;</li><li>Diagnose the reported issue, arrange spare parts and complete the requested service;</li><li>Maintain service records, resolve complaints and improve our quality and customer experience;</li><li>Prevent fraud, misuse or unsafe service requests; and</li><li>Meet our legal, accounting, tax and regulatory obligations.</li></ul><p>We do not sell, rent or trade your personal information to third parties for their independent marketing purposes.</p></>],
    ["3. Sharing of Information", <><p>We share information only to the extent necessary to fulfil your request. This may include relevant contact, address and service details with our in-house team, assigned technicians and approved service or spare-parts partners. Each recipient is expected to use the information only for the relevant service activity and to maintain appropriate confidentiality.</p><p>We may also disclose information where required by law, a valid legal process, or where reasonably necessary to protect the rights, safety or property of LocalPintu, our customers or the public.</p></>],
    ["4. Cookies and Website Analytics", <p>Our website may use cookies and similar technologies to remember preferences, understand site performance and improve your browsing experience. You can manage or disable cookies through your browser settings. Some website functions may not work as intended if cookies are disabled.</p>],
    ["5. Data Security and Retention", <><p>We use reasonable administrative, technical and organisational measures to protect information against unauthorised access, loss, misuse, disclosure or alteration. No internet transmission or electronic-storage system is completely secure; therefore, absolute security cannot be guaranteed.</p><p>We retain information for as long as it is needed for service delivery, support, warranty, record-keeping, dispute resolution or legal compliance, after which it is securely deleted or anonymised where reasonably practicable.</p></>],
    ["6. External Links", <p>Our website may include links to third-party websites, maps or platforms. Their content and privacy practices are outside our control. Please review their privacy policies before providing any information to them.</p>],
    ["7. Your Choices and Contact", <p>You may ask us to update or correct your contact details, or raise a privacy concern, by contacting <Contact />. We may need to verify your identity before acting on a request.</p>],
    ["8. Changes to This Policy", <p>We may update this Privacy Policy when our practices, services or legal obligations change. The revised version will be posted on this page with an updated date. Continued use of our website or services after the update means you accept the revised policy.</p>],
  ]},
  "/terms-and-conditions": { eyebrow: "CLEAR TERMS, CONFIDENT SERVICE", title: "Terms & Conditions", intro: "These Terms & Conditions govern your use of LocalPintu's website and doorstep home and appliance repair services. By accessing our website, submitting a service request or accepting a service visit, you agree to these Terms.", sections: [
    ["1. Service Scope and Availability", <p>LocalPintu provides access to trained service professionals for home and office appliance repair, maintenance, installation and related services. Service coverage, appointment slots and technician availability vary by location, appliance type and operational capacity. We aim to provide timely service, but an estimated arrival time is not a guarantee and may change because of traffic, weather, job complexity or other circumstances beyond reasonable control.</p>],
    ["2. Booking and Customer Responsibilities", <><p>When placing a request, you must provide accurate appliance details, issue description, address, contact information and access instructions. You must ensure that the appliance and service area are safe, accessible and reasonably suitable for inspection or repair at the agreed time.</p><p>Please keep children, pets and unauthorised persons away from the work area where appropriate. If the appliance has been previously opened, modified or repaired by another person, you must inform the technician. LocalPintu may decline, pause or reschedule a job where conditions are unsafe, access is unavailable or the request falls outside the offered service scope.</p></>],
    ["3. Inspection, Estimates and Approval", <p>An initial inspection may be required before the exact repair solution and cost can be confirmed. The technician will explain the diagnosis, recommended work, applicable visit charge, labour charge and spare-parts cost before proceeding wherever reasonably possible. You are responsible for approving the work and charges before repair begins. Additional issues discovered during repair may require a revised estimate and your further approval.</p>],
    ["4. Pricing and Payment", <><p>Prices may vary based on the appliance model, fault complexity, parts required, location and service type. Applicable visit, inspection, labour, platform, tax and spare-parts charges will be communicated before work begins or as soon as the relevant information is available.</p><p>Payment is due immediately upon completion of approved work unless a different arrangement is confirmed by LocalPintu in writing. You should review the invoice or payment receipt at the time of service and promptly notify us of any concern.</p></>],
    ["5. Three-Month Service Support", <><p>For an eligible repair, LocalPintu provides three months of free service support for the same reported fault repaired by our technician. If that same issue reoccurs during the support period, we will arrange a revisit without an additional service-visit charge, subject to inspection and these Terms.</p><p>This support does not cover a different or unrelated fault, physical or accidental damage, misuse, pest or water damage, voltage fluctuations, power-supply issues, consumables, or failure caused by third-party work, improper use or external conditions. A replacement part is covered only in accordance with the applicable manufacturer or supplier warranty, if any.</p></>],
    ["6. Limitation of Liability", <p>To the maximum extent permitted by applicable law, LocalPintu is responsible only for the service work actually performed. We are not liable for pre-existing defects, normal wear and tear, manufacturer defects, concealed damage, data loss, indirect or consequential loss, or future failures unrelated to our service. Nothing in these Terms limits liability that cannot legally be excluded.</p>],
    ["7. Intellectual Property", <p>All content on the LocalPintu website—including our name, logo, text, photographs, graphics, design and other materials—is owned by or licensed to LocalPintu and protected by applicable intellectual-property laws. It may not be copied, republished, modified or commercially used without prior written permission.</p>],
    ["8. Changes and Contact", <p>We may revise these Terms from time to time. The current version will be posted on this page. For a question about these Terms or a service booking, contact us at <Contact />.</p>],
  ]},
  "/refund-policy": { eyebrow: "TRANSPARENT, FAIR AND SIMPLE", title: "Refund Policy", intro: "This Refund Policy explains when charges may be refundable for LocalPintu doorstep services. It should be read together with our Terms & Conditions and Cancellation Policy.", sections: [
    ["1. Service Visit and Inspection Charges", <p>The service visit or inspection charge is generally non-refundable once a technician has been dispatched, has travelled to your location, or has inspected the appliance. This charge covers professional time, travel and diagnosis, even if you choose not to proceed with the repair after inspection.</p>],
    ["2. Completed Repair Services", <p>Once approved repair work is completed and the appliance is demonstrated as functioning for the reported issue at the time of service, labour and service charges are non-refundable. If the same repaired issue returns within the applicable three-month service-support period, please contact us promptly so that we can arrange an eligible revisit in accordance with our Terms & Conditions.</p>],
    ["3. Spare Parts", <p>Spare parts are billed separately. Parts that have been opened, installed or used are generally non-refundable because they cannot be safely reused or returned. If an installed part is found defective and is covered by a manufacturer or supplier warranty, we will assist with replacement under that warranty's terms. This is a replacement remedy and does not automatically create a cash-refund entitlement.</p>],
    ["4. Eligible Refunds", <p>A refund may be considered where LocalPintu cancels a prepaid booking before a service visit, where an amount was charged in error, or in another exceptional situation approved by our support team after review. We may request booking details, proof of payment or other reasonable information to verify the claim.</p>],
    ["5. Refund Method and Timeline", <p>Approved refunds are normally returned to the original payment method. After approval, the refund is generally initiated within 7–10 working days; the final credit time can depend on your bank, card issuer, UPI provider or payment gateway. Cash payments, where refundable, may require an alternative verified method.</p>],
    ["6. How to Request a Review", <p>To request a refund review, contact us at <Contact /> with your booking ID, registered mobile number, invoice or payment reference, and a brief description of the concern. Raising a request does not by itself guarantee a refund; each request is reviewed against the service record and this Policy.</p>],
  ]},
  "/cancellation-policy": { eyebrow: "FLEXIBLE BOOKINGS, CLEAR CHARGES", title: "Cancellation Policy", intro: "We understand that plans can change. This Cancellation Policy sets out how to cancel or reschedule a LocalPintu service request and when a service visit charge may apply.", sections: [
    ["1. Cancellation Before Technician Assignment or Dispatch", <p>You may cancel a service request without cancellation charges before a technician has been assigned or dispatched. If you made an eligible advance payment, it will be handled under our Refund Policy.</p>],
    ["2. Cancellation After Dispatch or Travel Has Started", <p>If a technician has been assigned and has started travelling to your location, a service visit charge may apply to cover travel time and professional availability. Our support team can confirm the status of your booking and any applicable charge when you contact us.</p>],
    ["3. Cancellation After Arrival", <p>If the technician has arrived at the stated address and you decide not to proceed, the service visit or inspection charge remains payable. This applies even where no repair is ultimately carried out, because the visit, travel and diagnosis time have already been committed.</p>],
    ["4. Cancellation During Repair", <p>Once repair work has begun, or a spare part has been opened, ordered specifically for your job or installed with your approval, the booking cannot be cancelled without payment for the work completed and applicable parts. The technician will explain any additional work that requires approval before proceeding.</p>],
    ["5. Unavailability, Incorrect Address or Unsafe Access", <p>If the customer cannot be reached, the address or appliance information is materially incorrect, the premises are locked, or safe access is not available at the scheduled visit, the visit may be treated as completed and a service visit charge may apply. Please notify us as early as possible if your plans change.</p>],
    ["6. Rescheduling", <p>You may reschedule one appointment without charge when you inform us at least one hour before the scheduled visit time and a suitable alternative slot is available. Repeated late rescheduling or cancellation may result in a visit charge, particularly after technician dispatch.</p>],
    ["7. Company-Initiated Cancellation", <p>In rare cases, LocalPintu may need to cancel or reschedule a booking because of technician unavailability, severe weather, safety concerns, service-area limitations or operational reasons. We will notify you as soon as reasonably possible. No service visit charge will apply where we cancel before service is delivered, and eligible prepayments will be addressed under our Refund Policy.</p>],
    ["8. Contact Us", <p>For a cancellation or rescheduling request, please contact us at <Contact /> and share your booking ID and registered mobile number.</p>],
  ]},
};
export default function LegalPage(){const{pathname}=useLocation();const policy=policies[pathname]||policies["/privacy-policy"];return <><Nav/><main className="legal-page"><section className="legal-hero"><div><span>{policy.eyebrow}</span><h1>{policy.title}</h1><p>{policy.intro}</p><small>Last updated: 13 September 2026</small></div></section><section className="legal-content"><aside><strong>LocalPintu policies</strong><Link to="/privacy-policy">Privacy Policy</Link><Link to="/terms-and-conditions">Terms &amp; Conditions</Link><Link to="/refund-policy">Refund Policy</Link><Link to="/cancellation-policy">Cancellation Policy</Link></aside><article>{policy.sections.map(([heading,content])=><section key={heading}><h2>{heading}</h2>{content}</section>)}<section className="legal-contact"><h2>Contact LocalPintu</h2><p>LocalPintu Repair Services<br/>1st Floor, 11–12 Coral Tower, Narendra Nagar, Sodala, Jaipur, Rajasthan 302019<br/>Email: <a href="mailto:info@localpintu.com">info@localpintu.com</a> · Phone: <a href="tel:+917023320977">+91 70233 20977</a></p></section></article></section></main><Footer/></>}
