import { lazy, Suspense, useEffect, useState } from "react";
import { Navigate, Route, Routes, useLocation, useParams } from "react-router-dom";

import ProtectedRoute from "./components/ProtectedRoute";
import ScrollProgress from "./components/ScrollProgress";
import { SkeletonGrid } from "./components/AsyncStates";
import useScrollReveal from "./hooks/useScrollReveal";
import "./styles/scrollProgress.css";
import "./styles/sonner.css";
import RouteSeo from "./components/RouteSeo";
import Analytics from "./components/Analytics";
import MobileBottomNav from "./components/MobileBottomNav";
import "./styles/mobileApp.css";
const LegalPage=lazy(()=>import("./pages/legal"));
const Toaster=lazy(()=>import("sonner").then((module)=>({default:module.Toaster})));const Home=lazy(()=>import("./pages/home"));const AboutUs=lazy(()=>import("./pages/aboutUs"));const BlogPage=lazy(()=>import("./pages/blog"));const BlogDetails=lazy(()=>import("./pages/blogDetails"));const ContactUsPage=lazy(()=>import("./pages/contactUs"));const Faqs=lazy(()=>import("./pages/faqs"));const BookingSuccess=lazy(()=>import("./pages/bookingSuccess"));const BookingDetails=lazy(()=>import("./pages/bookingDetails"));const NotFound=lazy(()=>import("./pages/notFound"));const CartPage=lazy(()=>import("./pages/cart"));const CheckoutPage=lazy(()=>import("./pages/checkout"));const OrdersPage=lazy(()=>import("./pages/orders"));
const auth=()=>import("./pages/auth");const SignupPage=lazy(()=>auth().then((module)=>({default:module.SignupPage})));const LoginPage=lazy(()=>auth().then((module)=>({default:module.LoginPage})));const ProfilePage=lazy(()=>auth().then((module)=>({default:module.ProfilePage})));const ChangePasswordPage=lazy(()=>auth().then((module)=>({default:module.ChangePasswordPage})));
const flow=()=>import("./pages/serviceFlow");const ServiceCategoriesPage=lazy(()=>flow().then((module)=>({default:module.ServiceCategoriesPage})));
function LegacyServiceFlowRedirect(){const{serviceSlug,categorySlug}=useParams();return <Navigate to={`/applications/${serviceSlug}?category=${encodeURIComponent(categorySlug)}`} replace/>}
function TechnicianPanelRedirect(){useEffect(()=>{const local=["localhost","127.0.0.1"].includes(window.location.hostname);window.location.replace(import.meta.env.VITE_TECHNICIAN_PANEL_URL||(local?"http://localhost:5175":"https://technician.localpintu.com"))},[]);return <main className="route-loading">Opening technician panel...</main>}
function App(){useScrollReveal();const location=useLocation();const[toastReady,setToastReady]=useState(false);const isAuthRoute=["/login","/signup","/change-password"].includes(location.pathname);useEffect(()=>{window.scrollTo({top:0,behavior:"auto"})},[location.pathname]);useEffect(()=>{const ready=()=>setToastReady(true);window.addEventListener("localpintu:toast",ready);return()=>window.removeEventListener("localpintu:toast",ready)},[]);return <><RouteSeo/><Analytics/><Suspense fallback={null}>{toastReady&&<Toaster position="top-right" richColors closeButton expand={false} visibleToasts={4} toastOptions={{ duration:4200,className:"localpintu-toast" }}/>}</Suspense><ScrollProgress/><div id="main-content" tabIndex="-1" key={location.pathname} className="page-transition"><Suspense fallback={<main className="route-loading"><SkeletonGrid count={6}/></main>}><Routes location={location}><Route path="/" element={<Home/>}/><Route path="/about" element={<AboutUs/>}/><Route path="/blogs" element={<BlogPage/>}/><Route path="/blogs/:blogSlug" element={<BlogDetails/>}/><Route path="/contact" element={<ContactUsPage/>}/><Route path="/faqs" element={<Faqs/>}/><Route path="/privacy-policy" element={<LegalPage/>}/><Route path="/terms-and-conditions" element={<LegalPage/>}/><Route path="/refund-policy" element={<LegalPage/>}/><Route path="/cancellation-policy" element={<LegalPage/>}/><Route path="/applications" element={<Navigate to="/#home-services" replace/>}/><Route path="/applications/:serviceSlug" element={<ServiceCategoriesPage/>}/><Route path="/applications/:serviceSlug/:categorySlug/*" element={<LegacyServiceFlowRedirect/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/checkout" element={<ProtectedRoute><CheckoutPage/></ProtectedRoute>}/><Route path="/book-service" element={<Navigate to="/cart" replace/>}/><Route path="/signup" element={<SignupPage/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/profile" element={<ProtectedRoute><ProfilePage/></ProtectedRoute>}/><Route path="/orders" element={<ProtectedRoute><OrdersPage/></ProtectedRoute>}/><Route path="/change-password" element={<ProtectedRoute><ChangePasswordPage/></ProtectedRoute>}/><Route path="/booking-success/:bookingId" element={<BookingSuccess/>}/><Route path="/booking-details/:bookingId" element={<BookingDetails/>}/><Route path="/technician/login" element={<TechnicianPanelRedirect/>}/><Route path="/technician/dashboard" element={<TechnicianPanelRedirect/>}/><Route path="/technician/jobs/:jobId" element={<TechnicianPanelRedirect/>}/><Route path="*" element={<NotFound/>}/></Routes></Suspense></div>{!isAuthRoute&&<MobileBottomNav/>}</>}
export default App;
